"""empty message

Revision ID: 6c9cf5744d3d
Revises: c14a885db246
Create Date: 2021-05-18 13:52:19.071880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c9cf5744d3d'
down_revision = 'c14a885db246'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_avatar', sa.String(length=20), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_name', sa.String(length=16), nullable=False),
    sa.Column('team_description', sa.String(length=32), nullable=False),
    sa.Column('teammates', sa.String(length=16), nullable=False),
    sa.Column('project_name', sa.String(length=16), nullable=False),
    sa.Column('project_pic1', sa.String(length=70), nullable=False),
    sa.Column('project_pic2', sa.String(length=70), nullable=True),
    sa.Column('project_pic3', sa.String(length=70), nullable=True),
    sa.Column('project_pic4', sa.String(length=70), nullable=True),
    sa.Column('project_description', sa.Text(length=120), nullable=False),
    sa.Column('publish_time', sa.DateTime(), nullable=False),
    sa.Column('publisher_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['publisher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_publish_time'), 'projects', ['publish_time'], unique=False)
    op.create_index(op.f('ix_projects_team_name'), 'projects', ['team_name'], unique=False)
    op.create_table('like_registrations',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('like_registrations')
    op.drop_index(op.f('ix_projects_team_name'), table_name='projects')
    op.drop_index(op.f('ix_projects_publish_time'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
